FROM ros:jazzy

# Install ur_robot_driver
RUN apt-get update && apt-get install -y \
    ros-jazzy-ur-robot-driver \
	ros-jazzy-ur-description \
    ros-jazzy-rmw-cyclonedds-cpp \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]