FROM ros_ur_base:latest

# GUI and development tools
RUN apt-get update && apt-get install -y \
    ros-jazzy-ur-moveit-config \
    ros-jazzy-rviz2 \
    ros-jazzy-rqt \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
